### ISSUE TITLE
Agregar seccion Quienes Somos

### ISSUE THREAD

**Issue by NicolasRuiz81** [davidspuler/Proyecto-Full-Stacks#25]
Subir la información para la sección Quienes Somos de la pagina web

**Comment by matiassorrentino** [comment]
QUIENES SOMOS

CONOCIENDO CÓRDOBA 

	Somos una empresa de viajes y turismo localizada en la Ciudad de Córdoba, dedicada a brindar asesoramiento integral en el rubro. Nacimos con el sueño de ofrecer a los viajeros toda nuestra experiencia y capacidad en el área, brindando un servicio de alta calidad y adaptándonos a las exigencias de hoy.
	Contamos con una amplia variedad de ofertas y paquetes turísticos personalizados que el cliente podrá evaluar y cotizar a través de nuestro sitio web o realizar consultas y dejar opiniones por nuestras redes sociales, respondiendo de manera inmediata a los requerimientos de los clientes.

	Nuestra empresa está totalmente orientada hacia las necesidades del cliente, teniendo en cuenta sus preferencias y cultura. Priorizamos siempre su seguridad y que sea una estadía memorable, por eso le ofrecemos comodidad y conveniencia económica en todo momento.

VALORES: La capacitación, dedicación y óptima predisposición son las razones principales por las que esta agencia de viajes se ha desarrollado como una empresa singular y diferente al resto. La innovación permanente, la creatividad y la orientación al cliente son valores fundamentales que plasmamos en nuestra forma de trabajar, persiguiendo el objetivo de marcar la diferencia en todo momento.

MISIÓN: Nuestro objetivo es obtener la satisfacción y superar las expectativas de los clientes para seguir creciendo. Estamos convencidos de que cada tarea debe estar dirigida a dar respuesta a la confianza que ellos depositan en nosotros.

VISIÓN: Queremos ser la agencia de viajes líder en Argentina distinguida por la atención personalizada al cliente y la garantía de un viaje memorable en familia, en pareja o con amigos.

	Ponemos a su disposición la solución integral para hacer de sus viajes por la Provincia de Córdoba como una experiencia única. Por ello, contamos con la infraestructura y la tecnología adecuada para responder de manera ágil a la demanda de los viajeros.
	Si su anhelo es vivir momentos maravillosos, confié en nosotros y prepárese para disfrutar de un viaje inolvidable.
