### ISSUE TITLE
Modificar el Menú principal de la pagina. 

### ISSUE THREAD

**Issue by NicolasRuiz81** [davidspuler/Proyecto-Full-Stacks#28]
Crear un duplicado de alguna pagina y agregar en ella un ejemplo de un menú responsive creado con bootstrap para evaluar el reemplazo del menú actual por el responsive
Tener en cuenta todas las vinculaciones ya creadas para mantener la funcionalidad de la pagina.

**Comment by GalarzaBrian** [comment]
tarea finalizada
