### ISSUE TITLE
Planning - Sprint 2

### ISSUE THREAD

**Issue by NicolasRuiz81** [davidspuler/Proyecto-Full-Stacks#29]
Dejamos fijada la fecha 24/10/22 para realizar el sprint planning, quedaria solo acordar el horario.
En la reunion charlamos sobre los temas a realizar en el sprint, y realizamos una division de tareas para mejor organizacion.

Temas pedidos para este sprint (Product Backlog):

Sitio funcional en hosting remoto de Sitio Institucional en WordPress (Este punto es para presentar al Empresa Ficticia que el grupo conforma, por lo que es parte indirecta del Proyecto. Pueden crear una sección en la Wiki con los registros de este sitio).
Frontend 
Funcionalidad con JavaScript en formularios
En subcarpeta (subdominio) y opcional linkeado al repositorio de GitHub/ GitHub Actions.
Backend
Script de la BD en MySQL
Consultas : Insert - Select - Update - JOIN
Modelo de Caso de Uso de cada modularización.(mínimo 1 CRUD (Python) y listado de movimientos/historial, por ejemplo)

Pueden sugerir un horario para la reunion por aca.

Gracias!!

**Comment by gusscamp22** [comment]
hora de la reunion 22.00 horas
