### ISSUE TITLE
Compra del hosting

### ISSUE THREAD

**Issue by NicolasRuiz81** [davidspuler/Proyecto-Full-Stacks#37]
Realizar las consultas para la compra del hosting para ver cual es el mas adecuado para la realización del trabajo. Consultarse entre ustedes para ver las distintas opciones.

**Comment by matiassorrentino** [comment]
Actividad Realizada, determinando con el grupo de trabajo la adquisición del Hosting y dominio, con el nombre de la empresa "SOFTECNO", URL: http://softecno.com.ar, mediante el cual se darán cumplimiento a las medidas solicitadas, para dar el correcto funcionamiento de la pagina.
